version: 2

models:
  - name: dim_listing_cleansed
    description: Table with cleansed Airbnb listings.
    columns:

      - name: listing_id
        description: Unique ID to Identify listings
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: ID for each host of any listings.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: type of room for rental.
        data_tests:
          - accepted_values:
              values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
      

      - name: minimum_nights
        description: '{{ doc("listing_min_nights") }}'
        data_tests:
          - positive_values
      
      - name: listing_url
        data_tests:
          - unique
          
      