version: 2

models:
  - name: dim_listing_cleansed
    columns:

      - name: listing_id
        data_tests:
          - unique
          - not_null

      - name: host_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        data_tests:
          - not_null

      - name: listing_url
        data_test:  
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']